### ISSUE TITLE
Proper cli

### ISSUE THREAD

**Issue by samintejas** [spaciery/mindmirror#5]
Commandline usage need to be improved 

something like this 

## Usage

by default running mindmirror will generate html pages from $XDG_CONFIG_HOME/mindmirror/content markdown with default css.

```sh
mindmirror
```

to generate with defaults and run the server 

```sh
mindmirror run
```

### generate using local folder

use flag l to generate from a local folder

```sh
mindmirror source --local ./content
```

```sh
mindmirror source --git "https://github.com/example/
```

**Comment by spaciery** [comment]
Added better cli using spf13/cobra and configuration support usign spf13/viper
